@path = localhost

@port = 8080

@pathproject = academico-web-api


### Lista todos os enderecos
GET Http://{{path}}:{{port}}/{{pathproject}}/enderecos

### Busca um endereco especifico por ID
GET Http://{{path}}:{{port}}/{{pathproject}}/enderecos/88

### Cria um endereco
POST Http://{{path}}:{{port}}/{{pathproject}}/enderecos
Content-Type: application/json

{
    "cep": 49300000,
    "bairro": "Macaé",
    "cidade": "Tobias Barreto",
    "estado": "SE",
    "rua": "Rua Da Feira"
},

### Atualiza um endereco
PUT  Http://{{path}}:{{port}}/{{pathproject}}/enderecos/88
Content-Type: application/json

{
    "cep": 49500000,
    "bairro": "Centro",
    "cidade": "Tobias Barreto",
    "estado": "SE",
    "rua": "Rua Da Ladeira"
},


### Deletar um endereco por ID
DELETE Http://{{path}}:{{port}}/{{pathproject}}/enderecos/88

### Atualizar Status do endereco(ATIVADO/DESATIVADO)
PUT  Http://{{path}}:{{port}}/{{pathproject}}/enderecos/89/status
Content-Type: text/plain

DESATIVO
