@path = localhost

@port = 8080

@pathproject = academico-web-api


### Lista todas as salas
GET Http://{{path}}:{{port}}/{{pathproject}}/salas

### Busca um sala especifico por ID
GET Http://{{path}}:{{port}}/{{pathproject}}/salas/9

### Cria uma sala
POST Http://{{path}}:{{port}}/{{pathproject}}/salas
Content-Type: application/json

{
    "capacidadeAlunos": 30,
    "laboratorio": false,
    "numeroSala": 3,
    "possuiArcondicionado": true,
    "quadroBranco": true
}

### Atualiza uma sala
PUT  Http://{{path}}:{{port}}/{{pathproject}}/salas/9
Content-Type: application/json

{
    "capacidadeAlunos": 35,
    "id": 2,
    "laboratorio": false,
    "numeroSala": 3,
    "possuiArcondicionado": true,
    "quadroBranco": true
},


### Deletar uma sala por ID
DELETE Http://{{path}}:{{port}}/{{pathproject}}/salas/9